version: '3'

services:

  angular-seed:
    build:
      context: .
      dockerfile: ./.docker/angular-seed.development.dockerfile
    command: npm start
    container_name: angular-seed-start
    image: angular-seed
    networks:
      - dev-network
    ports:
      - '8080:8080'

networks:
  dev-network:
    driver: bridge
